require:
  - rubocop-rails
  - rubocop-performance
# RSpec使うなら↓も（入れていれば）
#  - rubocop-rspec

AllCops:
  NewCops: enable              # 新しいCopは基本オン
  # TargetRubyVersion は .ruby-version / Gemfile から自動推定に任せる
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

# 好みの軽い調整（例）
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "spec/**/*"
